---
apiVersion: v1
kind: Namespace
metadata:
  name: jmeter-orchestrator
---
kind: Service
apiVersion: v1
metadata:
  name: jmeter-orchestrator-svc
  namespace: jmeter-orchestrator
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "http"
spec:
  selector:
    app: jmeter-orchestrator
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jmeter-orchestrator
  namespace: jmeter-orchestrator
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: jmeter-orchestrator
    spec:
      containers:
      - name: jmeter-orchestrator
        image: registry.gitlab.com/mdigiacomi-kubernetes/kubernetes-jmeter-orchestrator:latest
        imagePullPolicy: Always
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      imagePullSecrets:
        - name: gitlab-auth
