version: "3.0"

services:
    prom:
        image: registry.gitlab.com/mdigiacomi-kubernetes/kubernetes-jmeter-orchestrator:latest
        container_name: jmeter-manager
        expose:
        - 3000
        networks:
        - appnet
        - default
        labels:
        - "traefik.docker.network=web"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:jmeter-manager.hipsterconsulting.com"
        - "traefik.protocol=http"
        - "traefik.port=3000"
networks:
  appnet:
    external: true